<?php
echo('<select name="state" id="state-select" tabindex="5"');
if(!isset($_SESSION['state'])) echo(' style="display:none;"');
echo(' disabled required>');
echo('<option disabled');
if(!isset($_SESSION['state'])) echo(' selected');
echo('>State</option>');
echo('<option value="AL"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='AL') echo(' selected');
echo('>Alabama</option>');
echo('<option value="AK"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='AK') echo(' selected');
echo('>Alaska</option>');
echo('<option value="AS"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='AS') echo(' selected');
echo('>American Samoa</option>');
echo('<option value="AZ"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='AZ') echo(' selected');
echo('>Arizona</option>');
echo('<option value="AR"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='AR') echo(' selected');
echo('>Arkansas</option>');
echo('<option value="AA"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='AA') echo(' selected');
echo('>Armed Forces Americas</option>');
echo('<option value="AP"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='AP') echo(' selected');
echo('>Armed Forces Pacific</option>');
echo('<option value="AE"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='AE') echo(' selected');
echo('>Armed Forces Others</option>');
echo('<option value="CA"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='CA') echo(' selected');
echo('>California</option>');
echo('<option value="CO"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='CO') echo(' selected');
echo('>Colorado</option>');
echo('<option value="CT"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='CT') echo(' selected');
echo('>Connecticut</option>');
echo('<option value="DE"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='DE') echo(' selected');
echo('>Delaware</option>');
echo('<option value="DC"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='DC') echo(' selected');
echo('>District Of Columbia</option>');
echo('<option value="FL"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='FL') echo(' selected');
echo('>Florida</option>');
echo('<option value="GA"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='GA') echo(' selected');
echo('>Georgia</option>');
echo('<option value="GU"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='GU') echo(' selected');
echo('>Guam</option>');
echo('<option value="HI"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='HI') echo(' selected');
echo('>Hawaii</option>');
echo('<option value="ID"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='ID') echo(' selected');
echo('>Idaho</option>');
echo('<option value="IL"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='IL') echo(' selected');
echo('>Illinois</option>');
echo('<option value="IN"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='IN') echo(' selected');
echo('>Indiana</option>');
echo('<option value="IA"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='IA') echo(' selected');
echo('>Iowa</option>');
echo('<option value="KS"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='KS') echo(' selected');
echo('>Kansas</option>');
echo('<option value="KY"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='KY') echo(' selected');
echo('>Kentucky</option>');
echo('<option value="LA"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='LA') echo(' selected');
echo('>Louisiana</option>');
echo('<option value="ME"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='ME') echo(' selected');
echo('>Maine</option>');
echo('<option value="MD"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='MD') echo(' selected');
echo('>Maryland</option>');
echo('<option value="MA"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='MA') echo(' selected');
echo('>Massachusetts</option>');
echo('<option value="MI"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='MI') echo(' selected');
echo('>Michigan</option>');
echo('<option value="MN"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='MN') echo(' selected');
echo('>Minnesota</option>');
echo('<option value="MS"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='MS') echo(' selected');
echo('>Mississippi</option>');
echo('<option value="MO"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='MO') echo(' selected');
echo('>Missouri</option>');
echo('<option value="MT"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='MT') echo(' selected');
echo('>Montana</option>');
echo('<option value="NE"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='NE') echo(' selected');
echo('>Nebraska</option>');
echo('<option value="NV"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='NV') echo(' selected');
echo('>Nevada</option>');
echo('<option value="NH"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='NH') echo(' selected');
echo('>New Hampshire</option>');
echo('<option value="NJ"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='NJ') echo(' selected');
echo('>New Jersey</option>');
echo('<option value="NM"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='NM') echo(' selected');
echo('>New Mexico</option>');
echo('<option value="NY"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='NY') echo(' selected');
echo('>New York</option>');
echo('<option value="NC"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='NC') echo(' selected');
echo('>North Carolina</option>');
echo('<option value="ND"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='ND') echo(' selected');
echo('>North Dakota</option>');
echo('<option value="MP"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='MP') echo(' selected');
echo('>Northern Mariana Islands</option>');
echo('<option value="OH"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='OH') echo(' selected');
echo('>Ohio</option>');
echo('<option value="OK"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='OK') echo(' selected');
echo('>Oklahoma</option>');
echo('<option value="OR"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='OR') echo(' selected');
echo('>Oregon</option>');
echo('<option value="PA"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='PA') echo(' selected');
echo('>Pennsylvania</option>');
echo('<option value="PR"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='PR') echo(' selected');
echo('>Puerto Rico</option>');
echo('<option value="RI"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='RI') echo(' selected');
echo('>Rhode Island</option>');
echo('<option value="SC"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='SC') echo(' selected');
echo('>South Carolina</option>');
echo('<option value="SD"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='SD') echo(' selected');
echo('>South Dakota</option>');
echo('<option value="TN"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='TN') echo(' selected');
echo('>Tennessee</option>');
echo('<option value="TX"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='TX') echo(' selected');
echo('>Texas</option>');
echo('<option value="UM"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='UM') echo(' selected');
echo('>United States Minor Outlying Islands</option>');
echo('<option value="UT"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='UT') echo(' selected');
echo('>Utah</option>');
echo('<option value="VT"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='VT') echo(' selected');
echo('>Vermont</option>');
echo('<option value="VI"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='VI') echo(' selected');
echo('>Virgin Islands</option>');
echo('<option value="VA"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='VA') echo(' selected');
echo('>Virginia</option>');
echo('<option value="WA"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='WA') echo(' selected');
echo('>Washington</option>');
echo('<option value="WV"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='WV') echo(' selected');
echo('>West Virginia</option>');
echo('<option value="WI"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='WI') echo(' selected');
echo('>Wisconsin</option>');
echo('<option value="WY"');
if(isset($_SESSION['state'])&&$_SESSION['state']=='WY') echo(' selected');
echo('>Wyoming</option>');
echo('</select>');
?>